name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build app
        run: |
          # Add commands to build your app here
          # For example, if you're using npm:
          # npm install
          # npm run build
          # Adjust this command as per your build process

      - name: Send translation file to server and receive response
        run: |
         fetch('https://translation-server-8qv5.onrender.com/getTranslation',{method:'POST',headers:{'Content-Type':'application/json'},body:{data:JSON.stringify(require('./public/locales/en/translation.json')),reqLanguage:"es"}}).then(response=>response.json()).then(data=>{const fs=require('fs');fs.writeFileSync('./public/locales/es/translation.json',JSON.stringify(data));console.log('Spanish translation received and saved.');git add public/locales/es/translation.json;git commit -m "Update Spanish translation";git push}).catch(error=>{console.error('Error:',error);process.exit(1);});


