name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build app
        run: |
          # Add commands to build your app here
          # For example, if you're using npm:
          # npm install
          # npm run build
          # Adjust this command as per your build process
      - name: Post english json
        id:   myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://translation-server-8qv5.onrender.com/'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"data":{"submit":"Submit"},"reqLanguage":"es"}'
      - name: Show Response
        run: |
            echo ${{ steps.myRequest.outputs.response }}


