name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build app
        run: |
          # Add commands to build your app here
          # For example, if you're using npm:
          # npm install
          # npm run build
          # Adjust this command as per your build process
      - name: Post english json
        id:   myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://translation-server-8qv5.onrender.com/getTranslation'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"data":{"submit":"Submit"},"reqLanguage":"es"}'
      - name: Show Response
        run: |
            echo 'Showing API Response...'
            echo ${{ steps.myRequest.outputs.response }}
      - name: Create spanish directory
        run: |
            mkdir public/locales/es
            touch public/locales/es/translation.json
            JSON_RESPONSE=${{ steps.myRequest.outputs.response }}
            DATA_VALUE=$(echo $JSON_RESPONSE | jq -r '.data')
            echo ${{ DATA_VALUE }} > public/locales/es/translation.json
      - uses: stefanzweifel/git-auto-commit-action@v5

